// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: KafkaProto.proto

package org.red5.server.kafka;

public final class KafkaProto {
    private KafkaProto() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface KafkaRTMPMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:KafkaRTMPMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 timestamp = 1;</code>
         * @return Whether the timestamp field is set.
         */
        boolean hasTimestamp();

        /**
         * <code>required int32 timestamp = 1;</code>
         * @return The timestamp.
         */
        int getTimestamp();

        /**
         * <code>required bytes buf = 2;</code>
         * @return Whether the buf field is set.
         */
        boolean hasBuf();

        /**
         * <code>required bytes buf = 2;</code>
         * @return The buf.
         */
        com.google.protobuf.ByteString getBuf();

        /**
         * <code>required int32 datatype = 3;</code>
         * @return Whether the datatype field is set.
         */
        boolean hasDatatype();

        /**
         * <code>required int32 datatype = 3;</code>
         * @return The datatype.
         */
        int getDatatype();
    }

    /**
     * Protobuf type {@code KafkaRTMPMessage}
     */
    public static final class KafkaRTMPMessage extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:KafkaRTMPMessage)
            KafkaRTMPMessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use KafkaRTMPMessage.newBuilder() to construct.
        private KafkaRTMPMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private KafkaRTMPMessage() {
            buf_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new KafkaRTMPMessage();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private KafkaRTMPMessage(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            timestamp_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            buf_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            datatype_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return org.red5.server.kafka.KafkaProto.internal_static_KafkaRTMPMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return org.red5.server.kafka.KafkaProto.internal_static_KafkaRTMPMessage_fieldAccessorTable.ensureFieldAccessorsInitialized(org.red5.server.kafka.KafkaProto.KafkaRTMPMessage.class, org.red5.server.kafka.KafkaProto.KafkaRTMPMessage.Builder.class);
        }

        private int bitField0_;

        public static final int TIMESTAMP_FIELD_NUMBER = 1;

        private int timestamp_;

        /**
         * <code>required int32 timestamp = 1;</code>
         * @return Whether the timestamp field is set.
         */
        public boolean hasTimestamp() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required int32 timestamp = 1;</code>
         * @return The timestamp.
         */
        public int getTimestamp() {
            return timestamp_;
        }

        public static final int BUF_FIELD_NUMBER = 2;

        private com.google.protobuf.ByteString buf_;

        /**
         * <code>required bytes buf = 2;</code>
         * @return Whether the buf field is set.
         */
        public boolean hasBuf() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required bytes buf = 2;</code>
         * @return The buf.
         */
        public com.google.protobuf.ByteString getBuf() {
            return buf_;
        }

        public static final int DATATYPE_FIELD_NUMBER = 3;

        private int datatype_;

        /**
         * <code>required int32 datatype = 3;</code>
         * @return Whether the datatype field is set.
         */
        public boolean hasDatatype() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>required int32 datatype = 3;</code>
         * @return The datatype.
         */
        public int getDatatype() {
            return datatype_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasTimestamp()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasBuf()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDatatype()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeInt32(1, timestamp_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeBytes(2, buf_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeInt32(3, datatype_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, timestamp_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, buf_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, datatype_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.red5.server.kafka.KafkaProto.KafkaRTMPMessage)) {
                return super.equals(obj);
            }
            org.red5.server.kafka.KafkaProto.KafkaRTMPMessage other = (org.red5.server.kafka.KafkaProto.KafkaRTMPMessage) obj;

            if (hasTimestamp() != other.hasTimestamp())
                return false;
            if (hasTimestamp()) {
                if (getTimestamp() != other.getTimestamp())
                    return false;
            }
            if (hasBuf() != other.hasBuf())
                return false;
            if (hasBuf()) {
                if (!getBuf().equals(other.getBuf()))
                    return false;
            }
            if (hasDatatype() != other.hasDatatype())
                return false;
            if (hasDatatype()) {
                if (getDatatype() != other.getDatatype())
                    return false;
            }
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasTimestamp()) {
                hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
                hash = (53 * hash) + getTimestamp();
            }
            if (hasBuf()) {
                hash = (37 * hash) + BUF_FIELD_NUMBER;
                hash = (53 * hash) + getBuf().hashCode();
            }
            if (hasDatatype()) {
                hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
                hash = (53 * hash) + getDatatype();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.red5.server.kafka.KafkaProto.KafkaRTMPMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code KafkaRTMPMessage}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:KafkaRTMPMessage)
                org.red5.server.kafka.KafkaProto.KafkaRTMPMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return org.red5.server.kafka.KafkaProto.internal_static_KafkaRTMPMessage_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return org.red5.server.kafka.KafkaProto.internal_static_KafkaRTMPMessage_fieldAccessorTable.ensureFieldAccessorsInitialized(org.red5.server.kafka.KafkaProto.KafkaRTMPMessage.class, org.red5.server.kafka.KafkaProto.KafkaRTMPMessage.Builder.class);
            }

            // Construct using org.red5.server.kafka.KafkaProto.KafkaRTMPMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                timestamp_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                buf_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                datatype_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return org.red5.server.kafka.KafkaProto.internal_static_KafkaRTMPMessage_descriptor;
            }

            @java.lang.Override
            public org.red5.server.kafka.KafkaProto.KafkaRTMPMessage getDefaultInstanceForType() {
                return org.red5.server.kafka.KafkaProto.KafkaRTMPMessage.getDefaultInstance();
            }

            @java.lang.Override
            public org.red5.server.kafka.KafkaProto.KafkaRTMPMessage build() {
                org.red5.server.kafka.KafkaProto.KafkaRTMPMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.red5.server.kafka.KafkaProto.KafkaRTMPMessage buildPartial() {
                org.red5.server.kafka.KafkaProto.KafkaRTMPMessage result = new org.red5.server.kafka.KafkaProto.KafkaRTMPMessage(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.timestamp_ = timestamp_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.buf_ = buf_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.datatype_ = datatype_;
                    to_bitField0_ |= 0x00000004;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.red5.server.kafka.KafkaProto.KafkaRTMPMessage) {
                    return mergeFrom((org.red5.server.kafka.KafkaProto.KafkaRTMPMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.red5.server.kafka.KafkaProto.KafkaRTMPMessage other) {
                if (other == org.red5.server.kafka.KafkaProto.KafkaRTMPMessage.getDefaultInstance())
                    return this;
                if (other.hasTimestamp()) {
                    setTimestamp(other.getTimestamp());
                }
                if (other.hasBuf()) {
                    setBuf(other.getBuf());
                }
                if (other.hasDatatype()) {
                    setDatatype(other.getDatatype());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasTimestamp()) {
                    return false;
                }
                if (!hasBuf()) {
                    return false;
                }
                if (!hasDatatype()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                org.red5.server.kafka.KafkaProto.KafkaRTMPMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.red5.server.kafka.KafkaProto.KafkaRTMPMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int timestamp_;

            /**
             * <code>required int32 timestamp = 1;</code>
             * @return Whether the timestamp field is set.
             */
            public boolean hasTimestamp() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required int32 timestamp = 1;</code>
             * @return The timestamp.
             */
            public int getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>required int32 timestamp = 1;</code>
             * @param value The timestamp to set.
             * @return This builder for chaining.
             */
            public Builder setTimestamp(int value) {
                bitField0_ |= 0x00000001;
                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 timestamp = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000001);
                timestamp_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString buf_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes buf = 2;</code>
             * @return Whether the buf field is set.
             */
            public boolean hasBuf() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required bytes buf = 2;</code>
             * @return The buf.
             */
            public com.google.protobuf.ByteString getBuf() {
                return buf_;
            }

            /**
             * <code>required bytes buf = 2;</code>
             * @param value The buf to set.
             * @return This builder for chaining.
             */
            public Builder setBuf(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                buf_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes buf = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearBuf() {
                bitField0_ = (bitField0_ & ~0x00000002);
                buf_ = getDefaultInstance().getBuf();
                onChanged();
                return this;
            }

            private int datatype_;

            /**
             * <code>required int32 datatype = 3;</code>
             * @return Whether the datatype field is set.
             */
            public boolean hasDatatype() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>required int32 datatype = 3;</code>
             * @return The datatype.
             */
            public int getDatatype() {
                return datatype_;
            }

            /**
             * <code>required int32 datatype = 3;</code>
             * @param value The datatype to set.
             * @return This builder for chaining.
             */
            public Builder setDatatype(int value) {
                bitField0_ |= 0x00000004;
                datatype_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 datatype = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearDatatype() {
                bitField0_ = (bitField0_ & ~0x00000004);
                datatype_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:KafkaRTMPMessage)
        }

        // @@protoc_insertion_point(class_scope:KafkaRTMPMessage)
        private static final org.red5.server.kafka.KafkaProto.KafkaRTMPMessage DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new org.red5.server.kafka.KafkaProto.KafkaRTMPMessage();
        }

        public static org.red5.server.kafka.KafkaProto.KafkaRTMPMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<KafkaRTMPMessage> PARSER = new com.google.protobuf.AbstractParser<KafkaRTMPMessage>() {
            @java.lang.Override
            public KafkaRTMPMessage parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new KafkaRTMPMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<KafkaRTMPMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<KafkaRTMPMessage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.red5.server.kafka.KafkaProto.KafkaRTMPMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_KafkaRTMPMessage_descriptor;

    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_KafkaRTMPMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\020KafkaProto.proto\"D\n\020KafkaRTMPMessage\022\021" + "\n\ttimestamp\030\001 \002(\005\022\013\n\003buf\030\002 \002(\014\022\020\n\010dataty" + "pe\030\003 \002(\005B#\n\025org.red5.server.kafkaB\nKafka" + "Proto" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_KafkaRTMPMessage_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_KafkaRTMPMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_KafkaRTMPMessage_descriptor, new java.lang.String[] { "Timestamp", "Buf", "Datatype", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
